// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: proto/cmdserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCmdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCmdRequest) Reset() {
	*x = RunCmdRequest{}
	mi := &file_proto_cmdserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCmdRequest) ProtoMessage() {}

func (x *RunCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCmdRequest.ProtoReflect.Descriptor instead.
func (*RunCmdRequest) Descriptor() ([]byte, []int) {
	return file_proto_cmdserver_proto_rawDescGZIP(), []int{0}
}

func (x *RunCmdRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type RunCmdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCmdResponse) Reset() {
	*x = RunCmdResponse{}
	mi := &file_proto_cmdserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCmdResponse) ProtoMessage() {}

func (x *RunCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmdserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCmdResponse.ProtoReflect.Descriptor instead.
func (*RunCmdResponse) Descriptor() ([]byte, []int) {
	return file_proto_cmdserver_proto_rawDescGZIP(), []int{1}
}

func (x *RunCmdResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunCmdResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_proto_cmdserver_proto protoreflect.FileDescriptor

const file_proto_cmdserver_proto_rawDesc = "" +
	"\n" +
	"\x15proto/cmdserver.proto\x12\tcmdserver\"!\n" +
	"\rRunCmdRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\"E\n" +
	"\x0eRunCmdResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode2L\n" +
	"\tCmdServer\x12?\n" +
	"\x06RunCmd\x12\x18.cmdserver.RunCmdRequest\x1a\x19.cmdserver.RunCmdResponse0\x01B3Z1github.com/edwin-Marrima/Tardigrade-runtime/protob\x06proto3"

var (
	file_proto_cmdserver_proto_rawDescOnce sync.Once
	file_proto_cmdserver_proto_rawDescData []byte
)

func file_proto_cmdserver_proto_rawDescGZIP() []byte {
	file_proto_cmdserver_proto_rawDescOnce.Do(func() {
		file_proto_cmdserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cmdserver_proto_rawDesc), len(file_proto_cmdserver_proto_rawDesc)))
	})
	return file_proto_cmdserver_proto_rawDescData
}

var file_proto_cmdserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cmdserver_proto_goTypes = []any{
	(*RunCmdRequest)(nil),  // 0: cmdserver.RunCmdRequest
	(*RunCmdResponse)(nil), // 1: cmdserver.RunCmdResponse
}
var file_proto_cmdserver_proto_depIdxs = []int32{
	0, // 0: cmdserver.CmdServer.RunCmd:input_type -> cmdserver.RunCmdRequest
	1, // 1: cmdserver.CmdServer.RunCmd:output_type -> cmdserver.RunCmdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cmdserver_proto_init() }
func file_proto_cmdserver_proto_init() {
	if File_proto_cmdserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cmdserver_proto_rawDesc), len(file_proto_cmdserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cmdserver_proto_goTypes,
		DependencyIndexes: file_proto_cmdserver_proto_depIdxs,
		MessageInfos:      file_proto_cmdserver_proto_msgTypes,
	}.Build()
	File_proto_cmdserver_proto = out.File
	file_proto_cmdserver_proto_goTypes = nil
	file_proto_cmdserver_proto_depIdxs = nil
}
