// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: proto/cmdserver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CmdServer_RunCmd_FullMethodName = "/cmdserver.CmdServer/RunCmd"
)

// CmdServerClient is the client API for CmdServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CmdServerClient interface {
	// RunCmd executes a shell command and streams its output back line by line.
	// The final message carries the process exit_code; all preceding messages
	// have exit_code = 0.
	RunCmd(ctx context.Context, in *RunCmdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunCmdResponse], error)
}

type cmdServerClient struct {
	cc grpc.ClientConnInterface
}

func NewCmdServerClient(cc grpc.ClientConnInterface) CmdServerClient {
	return &cmdServerClient{cc}
}

func (c *cmdServerClient) RunCmd(ctx context.Context, in *RunCmdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunCmdResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CmdServer_ServiceDesc.Streams[0], CmdServer_RunCmd_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunCmdRequest, RunCmdResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CmdServer_RunCmdClient = grpc.ServerStreamingClient[RunCmdResponse]

// CmdServerServer is the server API for CmdServer service.
// All implementations must embed UnimplementedCmdServerServer
// for forward compatibility.
type CmdServerServer interface {
	// RunCmd executes a shell command and streams its output back line by line.
	// The final message carries the process exit_code; all preceding messages
	// have exit_code = 0.
	RunCmd(*RunCmdRequest, grpc.ServerStreamingServer[RunCmdResponse]) error
	mustEmbedUnimplementedCmdServerServer()
}

// UnimplementedCmdServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCmdServerServer struct{}

func (UnimplementedCmdServerServer) RunCmd(*RunCmdRequest, grpc.ServerStreamingServer[RunCmdResponse]) error {
	return status.Error(codes.Unimplemented, "method RunCmd not implemented")
}
func (UnimplementedCmdServerServer) mustEmbedUnimplementedCmdServerServer() {}
func (UnimplementedCmdServerServer) testEmbeddedByValue()                   {}

// UnsafeCmdServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CmdServerServer will
// result in compilation errors.
type UnsafeCmdServerServer interface {
	mustEmbedUnimplementedCmdServerServer()
}

func RegisterCmdServerServer(s grpc.ServiceRegistrar, srv CmdServerServer) {
	// If the following call panics, it indicates UnimplementedCmdServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CmdServer_ServiceDesc, srv)
}

func _CmdServer_RunCmd_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunCmdRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CmdServerServer).RunCmd(m, &grpc.GenericServerStream[RunCmdRequest, RunCmdResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CmdServer_RunCmdServer = grpc.ServerStreamingServer[RunCmdResponse]

// CmdServer_ServiceDesc is the grpc.ServiceDesc for CmdServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CmdServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cmdserver.CmdServer",
	HandlerType: (*CmdServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunCmd",
			Handler:       _CmdServer_RunCmd_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/cmdserver.proto",
}
