FROM golang:1.25-alpine AS init-build

WORKDIR /init
COPY rootfs/kernel/ .
RUN go mod init init && go build --tags netgo --ldflags '-s -w -extldflags "-lm -lstdc++ -static"' -o init server.go

FROM golang:1.25-alpine AS server-build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/cmdserver/ ./cmd/cmdserver/
COPY proto/ ./proto/
RUN CGO_ENABLED=0 go build -ldflags '-s -w -extldflags "-lm -lstdc++ -static"' -o /server ./cmd/cmdserver/

FROM alpine:3.20
RUN apk add --no-cache curl ca-certificates htop tini python3

COPY --from=init-build /init/init /init
COPY --from=server-build /server /usr/local/bin/server
